[2025-10-08T04:25:54.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-08T04:25:54.633+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model manual__2025-10-08T04:20:14.712439+00:00 [queued]>
[2025-10-08T04:25:54.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model manual__2025-10-08T04:20:14.712439+00:00 [queued]>
[2025-10-08T04:25:54.655+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-08T04:25:54.676+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): retrain_model> on 2025-10-08 04:20:14.712439+00:00
[2025-10-08T04:25:54.688+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=262) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-08T04:25:54.692+0000] {standard_task_runner.py:64} INFO - Started process 265 to run task
[2025-10-08T04:25:54.691+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'restaurant_analytics', 'retrain_model', 'manual__2025-10-08T04:20:14.712439+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_dag.py', '--cfg-path', '/tmp/tmph812cn60']
[2025-10-08T04:25:54.696+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask retrain_model
[2025-10-08T04:25:54.795+0000] {task_command.py:426} INFO - Running <TaskInstance: restaurant_analytics.retrain_model manual__2025-10-08T04:20:14.712439+00:00 [running]> on host c34aac175a74
[2025-10-08T04:25:54.972+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='quantruong1918@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='restaurant_analytics' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T04:20:14.712439+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-08T04:20:14.712439+00:00'
[2025-10-08T04:25:54.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-08T04:25:54.978+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-08T04:25:54.980+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/spark/bin/spark-submit --master local[*] /opt/***/dags/train_lr.py']
[2025-10-08T04:25:55.001+0000] {subprocess.py:86} INFO - Output:
[2025-10-08T04:26:01.391+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-08T04:26:01.392+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/train_lr.py", line 2, in <module>
[2025-10-08T04:26:01.395+0000] {subprocess.py:93} INFO -     from pyspark.ml.feature import VectorAssembler
[2025-10-08T04:26:01.396+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/__init__.py", line 22, in <module>
[2025-10-08T04:26:01.397+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 40, in <module>
[2025-10-08T04:26:01.398+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 32, in <module>
[2025-10-08T04:26:01.399+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'numpy'
[2025-10-08T04:26:01.471+0000] {subprocess.py:93} INFO - 25/10/08 04:26:01 INFO ShutdownHookManager: Shutdown hook called
[2025-10-08T04:26:01.477+0000] {subprocess.py:93} INFO - 25/10/08 04:26:01 INFO ShutdownHookManager: Deleting directory /tmp/spark-6e8d6990-a558-4c2d-b53d-1d0f899495af
[2025-10-08T04:26:01.539+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-08T04:26:01.541+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-08T04:26:01.561+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-08T04:26:01.571+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=restaurant_analytics, task_id=retrain_model, run_id=manual__2025-10-08T04:20:14.712439+00:00, execution_date=20251008T042014, start_date=20251008T042554, end_date=20251008T042601
[2025-10-08T04:26:01.610+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 118 for task retrain_model (Bash command failed. The command returned a non-zero exit code 1.; 265)
[2025-10-08T04:26:01.660+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-08T04:26:01.688+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-08T04:26:01.691+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
