[2025-10-07T10:05:09.659+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-07T10:05:09.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-07T09:00:00+00:00 [queued]>
[2025-10-07T10:05:09.724+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-07T09:00:00+00:00 [queued]>
[2025-10-07T10:05:09.725+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-07T10:05:09.746+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): retrain_model> on 2025-10-07 09:00:00+00:00
[2025-10-07T10:05:09.757+0000] {standard_task_runner.py:64} INFO - Started process 4938 to run task
[2025-10-07T10:05:09.763+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'restaurant_analytics', 'retrain_model', 'scheduled__2025-10-07T09:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_dag.py', '--cfg-path', '/tmp/tmp8xr923h1']
[2025-10-07T10:05:09.769+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask retrain_model
[2025-10-07T10:05:09.908+0000] {task_command.py:426} INFO - Running <TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-07T09:00:00+00:00 [running]> on host 50743b1a3092
[2025-10-07T10:05:10.185+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='quantruong1918@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='restaurant_analytics' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-07T09:00:00+00:00'
[2025-10-07T10:05:10.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-07T10:05:10.194+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-07T10:05:10.198+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local[*] /opt/***/dags/train_lr.py']
[2025-10-07T10:05:10.244+0000] {subprocess.py:86} INFO - Output:
[2025-10-07T10:05:10.249+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: spark-submit: command not found
[2025-10-07T10:05:10.252+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-10-07T10:05:10.258+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-07T10:05:10.305+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-07T10:05:10.321+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=restaurant_analytics, task_id=retrain_model, run_id=scheduled__2025-10-07T09:00:00+00:00, execution_date=20251007T090000, start_date=20251007T100509, end_date=20251007T100510
[2025-10-07T10:05:10.355+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task retrain_model (Bash command failed. The command returned a non-zero exit code 127.; 4938)
[2025-10-07T10:05:10.417+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-07T10:05:10.446+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
