[2025-10-08T09:05:21.172+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-08T09:05:21.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-08T08:00:00+00:00 [queued]>
[2025-10-08T09:05:21.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-08T08:00:00+00:00 [queued]>
[2025-10-08T09:05:21.244+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-08T09:05:21.270+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): retrain_model> on 2025-10-08 08:00:00+00:00
[2025-10-08T09:05:21.306+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2064) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-08T09:05:21.312+0000] {standard_task_runner.py:64} INFO - Started process 2068 to run task
[2025-10-08T09:05:21.306+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'restaurant_analytics', 'retrain_model', 'scheduled__2025-10-08T08:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_dag.py', '--cfg-path', '/tmp/tmpjizryv1w']
[2025-10-08T09:05:21.316+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask retrain_model
[2025-10-08T09:05:21.547+0000] {task_command.py:426} INFO - Running <TaskInstance: restaurant_analytics.retrain_model scheduled__2025-10-08T08:00:00+00:00 [running]> on host 26440191eecc
[2025-10-08T09:05:21.797+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='quantruong1918@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='restaurant_analytics' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-08T08:00:00+00:00'
[2025-10-08T09:05:21.801+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-08T09:05:21.803+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-08T09:05:21.806+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/spark/bin/spark-submit --master local[*] /opt/***/dags/train_lr.py']
[2025-10-08T09:05:21.841+0000] {subprocess.py:86} INFO - Output:
[2025-10-08T09:05:27.912+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-08T09:05:27.913+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/train_lr.py", line 2, in <module>
[2025-10-08T09:05:27.916+0000] {subprocess.py:93} INFO -     from pyspark.ml.feature import VectorAssembler
[2025-10-08T09:05:27.917+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/__init__.py", line 22, in <module>
[2025-10-08T09:05:27.918+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 40, in <module>
[2025-10-08T09:05:27.921+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 32, in <module>
[2025-10-08T09:05:27.925+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'numpy'
[2025-10-08T09:05:28.013+0000] {subprocess.py:93} INFO - 25/10/08 09:05:28 INFO ShutdownHookManager: Shutdown hook called
[2025-10-08T09:05:28.020+0000] {subprocess.py:93} INFO - 25/10/08 09:05:28 INFO ShutdownHookManager: Deleting directory /tmp/spark-7ed707ec-b2a3-45f7-a2b4-4f7f286838a5
[2025-10-08T09:05:28.077+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-08T09:05:28.078+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-08T09:05:28.098+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-08T09:05:28.107+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=restaurant_analytics, task_id=retrain_model, run_id=scheduled__2025-10-08T08:00:00+00:00, execution_date=20251008T080000, start_date=20251008T090521, end_date=20251008T090528
[2025-10-08T09:05:28.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 177 for task retrain_model (Bash command failed. The command returned a non-zero exit code 1.; 2068)
[2025-10-08T09:05:28.163+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-08T09:05:28.193+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-08T09:05:28.196+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
